### ISSUE TITLE
[Question] Language customizations?

### ISSUE THREAD

**Issue by rubyFeedback** [benreu/PyGtk-Posting#6]
Hello there,

Is it possible to adapt this to different languages? Specifically I am wondering about
e. g. using german here; not for me, but for an elderly relative who could benefit.
(I have no problem with the english language myself, so this is really for others.)

I am not sure how much work it would be to use e. g. german labels rather than
english ones.

**Comment by benreu** [comment]
Based on https://stackoverflow.com/questions/10094335/ , there ought to be a way. Just from running some tests, it looks like there will be over 1000 GUI widgets to translate. Most of them are in the UI files.

If Germany is your country, you might want to take a peek at GnuAccounting. I used GnuAccounting before I wrote PyGtk Posting.

I have not put a lot of time into translations as of yet, as I thought the legal side of accounting might be more important. Namely, tax calculations and so forth. The tax calculations are done in Postgres. Upon app install, these would need to be set to the region the user lives in. Currently, they are fixed to USA.

If you have used PyGtk Posting, could you tell me if Postgres error codes are in German?
